const mongoose = require("mongoose");
const Joi = require("joi");

const tourSchema = new mongoose.Schema(
    {
        id: { type: Number },
        titleEn: { type: String, trim: true },
        titleAz: { type: String, trim: true },
        duration: { type: String },
        images: [{ type: String }],
        tripInfo: {
            accommodationEn: { type: String },
            accommodationAz: { type: String },
            departureCityEn: { type: String },
            departureCityAz: { type: String },
            arrivalCityEn: { type: String },
            arrivalCityAz: { type: String },
            bestSeasonEn: { type: String },
            bestSeasonAz: { type: String },
            guideEn: { type: String },
            guideAz: { type: String },
            language: { type: String },
            mealsEn: { type: String },
            mealsAz: { type: String },
            tourAvailabilityEn: { type: String },
            tourAvailabilityAz: { type: String },
            transportationEn: { type: String },
            transportationAz: { type: String },
            walkingHoursEn: { type: String },
            walkingHoursAz: { type: String },
            minimumAge: { type: Number },
            maximumAge: { type: Number },
            tripTypeEn: { type: String },
            tripTypeAz: { type: String },
            originalprice: { type: Number },
            discountedprice: { type: Number },
            discount: { type: Number }
        },
        destination: [{ type: mongoose.Schema.Types.ObjectId, ref: "Destination" }],
        activity: [{ type: mongoose.Schema.Types.ObjectId, ref: "Activity" }],
        overview: {
            titleEn: { type: String },
            titleAz: { type: String },
            descriptionEn: { type: String },
            descriptionAz: { type: String },
        },
        itinerary: {
            titleEn: { type: String },
            titleAz: { type: String },
            dayOneEn: { type: String },
            dayOneAz: { type: String },
            dayTwoEn: { type: String },
            dayTwoAz: { type: String },
            dayThreeEn: { type: String },
            dayThreeAz: { type: String },
            dayFourEn: { type: String },
            dayFourAz: { type: String },
            dayFiveEn: { type: String },
            dayFiveAz: { type: String },
            daySixEn: { type: String },
            daySixAz: { type: String },
            daySevenEn: { type: String },
            daySevenAz: { type: String },
        },
        cost: {
            titleEn: { type: String },
            titleAz: { type: String },
            descriptionEn: { type: String },
            descriptionAz: { type: String },
        },
        rating: { type: Number, default: 4.5, min: 1, max: 5 },
        createdAt: { type: Date, default: Date.now },
    },
    { timestamps: true }
);

const tourValidate = (tour) => {
    const schema = Joi.object({
        id: Joi.number(),
        titleEn: Joi.string(),
        titleAz: Joi.string(),
        duration: Joi.string(),
        images: Joi.array().items(Joi.string()),
        tripInfo: Joi.object({
            accommodationEn: Joi.string(),
            accommodationAz: Joi.string(),
            departureCityEn: Joi.string(),
            departureCityAz: Joi.string(),
            arrivalCityEn: Joi.string(),
            arrivalCityAz: Joi.string(),
            bestSeasonEn: Joi.string(),
            bestSeasonAz: Joi.string(),
            guideEn: Joi.string(),
            guideAz: Joi.string(),
            language: Joi.string(),
            mealsEn: Joi.string(),
            mealsAz: Joi.string(),
            tourAvailabilityEn: Joi.string(),
            tourAvailabilityAz: Joi.string(),
            transportationEn: Joi.string(),
            transportationAz: Joi.string(),
            walkingHoursEn: Joi.string(),
            walkingHoursAz: Joi.string(),
            minimumAge: Joi.number(),
            maximumAge: Joi.number(),
            tripTypeEn: Joi.string(),
            tripTypeAz: Joi.string(),
            originalprice: Joi.number(),
            discountedprice: Joi.number(),
            discount: Joi.number()
        }),
        activity: Joi.string(),
        destination: Joi.string(),
        overview: Joi.object({
            titleEn: Joi.string(),
            titleAz: Joi.string(),
            descriptionEn: Joi.string(),
            descriptionAz: Joi.string(),
        }),
        itinerary: Joi.object({
            titleEn: Joi.string(),
            titleAz: Joi.string(),
            dayOneAz: Joi.string(),
            dayOneEn: Joi.string(),
            dayTwoEn: Joi.string(),
            dayTwoAz: Joi.string(),
            dayThreeEn: Joi.string(),
            dayThreeAz: Joi.string(),
            dayFourEn: Joi.string(),
            dayFourAz: Joi.string(),
            dayFiveEn: Joi.string(),
            dayFiveAz: Joi.string(),
            daySixEn: Joi.string(),
            daySixAz: Joi.string(),
            daySevenEn: Joi.string(),
            daySevenAz: Joi.string(),
        }),
        cost: Joi.object({
            titleEn: Joi.string(),
            titleAz: Joi.string(),
            descriptionEn: Joi.string(),
            descriptionAz: Joi.string(),
        }),
        rating: Joi.number().min(1).max(5),
    });

    return schema.validate(tour);
};

module.exports = { Tour: mongoose.model("Tour", tourSchema), tourValidate };